type Events {
  heroId: String!
  events: [Event!]
}

type Event @embedded {
  year: String!
  title: String!
  description: String!
  imagePath: String!
}

type Query {
  eventsCollection: [Events!]
}
