[build]
  command = "yarn build"
  environment = {NODE_VERSION = "16.13.0"}
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "api/*"
  to = ".netlify/functions/:splat"
  status = 200