[build]
  command = "yarn build"
  publish = "dist"
  functions = "functions"
  [build.environment]
    NODE_VERSION = "18.17.1"
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"
    # prevent progress messages
    CI = "1"

[dev]
  targetPort = 3000

[[redirects]]
  from = "api/*"
  to = ".netlify/functions/:splat"
  status = 200

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true