[build]
  command = "yarn build"
  publish = "dist"
  functions = "functions"
  [build.environment]
    NODE_VERSION = "16.13.0"
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"
    # prevent progress messages
    CI = "1"

[[redirects]]
  from = "api/*"
  to = ".netlify/functions/:splat"
  status = 200

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.preBuild]
    enable = true  
    start = "yarn start"
    wait-on = "http://localhost:8888"
    wait-on-timeout = "30"
    record = true
    group = '1: testing develop site'
  [plugins.inputs.postBuild]
    enable = true
    record = true
    group = '2: testing built site'  
  [plugins.inputs]
    enable = false