name: Ping Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *' # Runs every 2 days at midnight UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run ping script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -c "
          import requests
          import os

          SUPABASE_URL = os.getenv('SUPABASE_URL')
          SUPABASE_KEY = os.getenv('SUPABASE_KEY')

          def ping_supabase():
              headers = {
                  'apikey': SUPABASE_KEY,
                  'Authorization': f'Bearer {SUPABASE_KEY}',
                  'Content-Type': 'application/json',
              }
              query = {
                'query': '''
                  query {
                    metaCollection {
                      edges {
                        hero: node {
                          id
                          heroId
                          name
                          menuBgImagePath
                          whiteLogoPath
                        }
                      }
                    }
                  }
                '''
              }
              response = requests.post(SUPABASE_URL, json=query, headers=headers)
              if response.status_code == 200:
                  print('Ping successful')
              else:
                  print('Ping failed', response.status_code, response.text)

          ping_supabase()
          "
